### ISSUE TITLE
Package not found on Packagist

### ISSUE THREAD

**Issue by guiassemany** [spatie/laravel-utm-forwarder#1]
Hey guys, today I tried to install this package in one of my projects using the command: 
`composer require spatie/laravel-analytics-tracker`

It didn't work and the message is:

`Could not find a matching version of package spatie/laravel-analytics-tracker. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (dev).`

I went to packagist and couldn't find this package there. Am I doing something wrong? 

Thanks in advance!

**Comment by betaselect** [comment]
I have the same issue. Thanks!

**Comment by AlexVanderbist** [comment]
Hi @guiassemany, @InWave,

This is an unfinished package. I'll put a notice in the readme and archive the repo. The code however should be as good as finished (but without tests or testing) so feel free to fork or copy paste it into your own project. There's really not that much to it ;) 

Good luck!
